ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc
- podman
- container

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

New_Keywords:
- allow
- remote
- via
- attackers
- arbitrary
- vulnerability
- execute
- file
- script
- parameter
- service
- code
- cause
- sql
- denial
- web
- users
- unspecified
- earlier
- vectors
- command
- site
- cross
- server
- local
- cve
- use
- overflow
- html
- multiple
- xss
- information
- inject
- buffer
- php
- injection
- craft
- note
- possibly
- unknown
- obtain
- request
- function
- vulnerabilities
- crash
- aka
- relate
- directory
- access
- windows
- properly
- attack
- application
- user
- memory
- privilege
- url
- long
- read
- dot
- index.php
- gain
- base
- authenticate
- message
- certain
- oracle
- different
- component
- sensitive
- bypass
- traversal
- microsoft
- include
- system
- action
- name
- http
- third
- party
- issue
- data
- module
- demonstrate
- detail
- id
- authentication
- string
- password
- control
- linux
- field
- trigger
- impact
- inclusion
- modify
- apple
- parameters
- kernel
- sp2
- error
- value
- os
- admin
- page
- corruption
- contain
- might
- mac
- handle
- candidate
- path
- 1.0
- stack
- manager
- affect
- security
- client
- internet
- number
- content
- versions
- enable
- create
- cisco
- java
- heap
- root
- ibm
- call
- sp1
- program
- process
- malformed
- large
- direct
- sequence
- search
- database
- set
- 2008
- format
- upload
- packet
- reference
- integer
- image
- argument
- list
- update
- adobe
- 2010
- 2006
- mail
- overwrite
- 2012
- object
- character
- network
- send
- enterprise
- firefox
- 2.0
- explorer
- 2007
- management
- port
- configuration
- invalid
- 2003
- document
- store
- log
- address
- header
- username
- make
- cms
- sp3
- run
- provenance
- daemon
- extension
- hp
- consumption
- mozilla
- 10
- involve
- assist
- conduct
- integrity
- null
- chrome
- solely
- variable
- free
- activex
- google
- permissions
- javascript
- account
- device
- player
- interface
- dispute
- could
- bug
- 5.0
- products
- default
- restrictions
- office
- check
- sun
- xp
- method
- intend
- build
- 2000
- session
- ftp
- 2011
- login
- ip
- context
- software
- 6.x
- tcp
- passwords
- confidentiality
- key
- implementation
- type
- open
- servers
- 4.0
- spoof
- symlink
- uri
- solaris
- perform
- packets
- tag
- pointer
- 2005
- 1.1
- 6.0
- length
- suite
- prevent
